                        <div class="row mbl">
                            <div class="col-lg-12">
                                        <div class="row">
											<div class="col-lg-8">
												<div class="panel panel-orange">
													<div class="panel-heading">Login</div>
													<div class="panel-body pan">
														<form action="" method="post">
														<div class="form-body pal">
														<?php if(isset($this->error) AND $this->error==true){ 
														if($this->error_m['uname']!='' AND $this->error_m['uname']!=null){
															?>
														<div class="alert alert-danger"><strong>UserName Error!</strong> <?php echo $this->error_m['uname']; ?></div>
															<?php 
														}
														if($this->error_m['pass']!='' AND $this->error_m['pass']!=null){
															?>
														<div class="alert alert-danger"><strong>PassWord Error!</strong> <?php echo $this->error_m['pass']; ?></div>
															<?php 
														}
														?>
														<?php } ?>
														</div>
														<div class="form-body pal">
															<div class="form-group">
																<div class="input-icon right">
																	<i class="fa fa-user"></i>
																	<input id="inputName" name="uname" type="text" placeholder="Username" class="form-control" required></div>
															</div>
															<div class="form-group">
																<div class="input-icon right">
																	<i class="fa fa-lock"></i>
																	<input id="inputPassword" name="password" type="password" placeholder="Password" class="form-control" required></div>
															</div>
														</div>
														<div class="form-actions text-right pal">
															<button type="submit" class="btn btn-primary">
																Login</button>
														</div>
														</form>
													</div>
												</div>
											</div>	
											<div class="col-lg-4">
												<div class="panel panel-blue" style="background:#fff;">
													<div class="panel-heading">Register</div>
													<div class="panel-body pan">
														<div class="form-body pal">
															<a href="signup.php">Don't you have account?</a>
														</div>
													</div>
												</div>
											</div>										
                                        </div>
                            </div>
                        </div>