<?php
if($this->error AND $this->error_m!="")
{
?>
<div class="row mbl">
	<div class="col-lg-12">
		<div class="alert alert-danger"><strong>Oops!</strong> <?php echo $this->error_m; ?></div>
	</div>
</div>
<?php
}
if($this->action_status AND $this->action_m!="")
{
?>
<div class="row mbl">
	<div class="col-lg-12">
		<div class="alert alert-success"><strong>Successfull Action!</strong> <?php echo $this->action_m; ?></div>
	</div>
</div>
<?php
}
?>
<div class="row mbl">
<?php
if($this->show_inbox)
{
?>
<script type="text/javascript">
function printContent(el){
	var restorepage = document.body.innerHTML;
	var printcontent = document.getElementById(el).innerHTML;


	document.body.innerHTML = printcontent+` <style>

@media print {
	.table-logo {
		border:1px solid #ccc !important;
		
  	}
    .table-logo th{
      display: block;
	  border: none !important;
	  width:300%;
    }

}

</style>`;
	window.print();
	document.body.innerHTML = restorepage;
}

</script>
<style>
@media screen {
  .table-logo {
    display: none;
  }
}
</style>
	<div class="col-sm-12 col-md-12">
		<div class="tab-content">
			<div id="home" class="tab-pane fade in active">
				<div class="list-group mail-box">

                    <form class="form-inline" method="get" action="transactions.php">
                        <div class="form-group">
                            <label for="from_date">From Date:</label>
                            <input type="datetime-local" class="form-control" id="from_date" name="from_date" value="<?= $_GET['from_date'] ?? null?>">
                        </div>
                        <div class="form-group">
                            <label for="to_date">to Date:</label>
                            <input type="datetime-local" class="form-control" id="to_date" name="to_date" value="<?= $_GET['to_date'] ?? null?>">
                        </div>
                        <button type="submit" class="btn btn-default">Filter</button>
                        <br>
                        <br>
                    </form>


				<button type="button" class="btn btn-primary" onclick="printContent('print')" style="margin-bottom: 20px;">Print the bellow report table</button>
                    <br>
				<div id="print">
				<div class="divFooter"></div>
					<table class="table table-hover table-bordered" >
						<thead>
							<tr class='table-logo' style="border: none !important;">
								<th colspan="17" style="border: none !important;">
									<img src="https://bookingparcel.com/logo.gif" >
								</th>
							</tr>
							<tr>
								<th>#</th>
								<th>Transaction ID</th>
								<th>Quote ID</th>
								<th>Amount (Currency)</th>
								<th>Transaction Type</th>
								<th>Description</th>
								<th>Date</th>
							</tr>
						</thead>
						<tbody>

<?php 
if(isset($this->Transactons_Info) AND $this->Transactons_Info!=null AND is_array($this->Transactons_Info) AND count($this->Transactons_Info) > 0)
{
	//$__c = ($this->items_per_page * ($this->page - 1)) + 1;
	$__c = $this->total_Res - ($this->items_per_page * ($this->page - 1));
	foreach($this->Transactons_Info as $Transacton)
	{
		echo "<tr class=\"".(($Transacton['type']==0 OR $Transacton['type']==3) ? "warning" : "success")."\">";
		echo '<td >'.$__c.'</td>';
		echo '<td >'.$Transacton['id'].'</td>';
		echo '<td >'.$Transacton['oref'].'</td>';
		echo '<td >'.$Transacton['amount'].'&nbsp;('.$Transacton['currency'].')</td>';
		echo '<td >'.($Transacton['type']==0 ? "Paid For Quote" : ($Transacton['type']==1 ? "Increasing The Deposite" : ($Transacton['type']==2 ? "Return Money Back" : "Difference"))).'</td>';
		echo '<td >'.$Transacton['description'].'</td>';
		echo '<td >'.date("Y/m/d H:i:s",$Transacton['timestamp']).'</td>';
		echo "</tr>";
		$__c--;
	}
}
else
{
	echo '<tr class="danger"><td colspan="7">No Transacton found.</td></tr>';
}
?>						
						</tbody>
					</table>
				</div>
				<?php echo $this->RenderPagination($this->page, $this->total_Page, $this->items_per_page, $this->total_Res); ?>
				</div>
				</div>
			</div>
		</div>
	</div>

<?php
}
?>
</div>
